from classes import *


def get_gcode(g):

  G0 = 'Rapid Motion Positioning'
  G0 = 'Rapid Motion Positioning'
  G1 = 'Linear Interpolation Motion'
  G2 = 'CW Circular Interpolation Motion'
  G3 = 'CCW Circular Interpolation Motion'
  G4 = 'Dwell'
  G9 = 'Exact Stop'
  G10	=	'Set Offsets'
  G14	=	'Secondary Spindle Swap'
  G15	=	'Secondary Spindle Swap Cancel'
  G17	=	'XY Plane'
  G18	=	'XZ Plane'
  G19	=	'YZ Plane'
  G20	=	'Select Inches'
  G21	=	'Select Metric'
  G28	=	'Return To Machine Zero Point'
  G29	=	'Return From Reference Point'
  G31	=	'Skip Function'
  G32	=	'Thread Cutting'
  G40	=	'Tool Nose Compensation Cancel'
  G41	=	'Tool Nose Compensation (TNC) Left'
  G42	=	'Tool Nose Compensation (TNC) Right'
  G43	=	'Tool Length Compensation + (Add)'
  G50	=	'Spindle Speed Limit'
  G50	=	'Set Global coordinate Offset FANUC'
  G52	=	'Set Local Coordinate System FANUC'
  G53	=	'Machine Coordinate Selection'
  G54	=	'Coordinate System #1 FANUC'
  G55	=	'Coordinate System #2 FANUC'
  G56	=	'Coordinate System #3 FANUC'
  G57	=	'Coordinate System #4 FANUC'
  G58	=	'Coordinate System #5 FANUC'
  G59	=	'Coordinate System #6 FANUC'
  G61	=	'Exact Stop Modal'
  G64	=	'Exact Stop Cancel G61'
  G65	=	'Macro Subprogram Call Option'
  G68	=	'Rotation'
  G69	=	'Cancel G68 Rotation'
  G70	=	'Finishing Cycle'
  G71	=	'O.D./I.D. Stock Removal Cycle'
  G72	=	'End Face Stock Removal Cycle'
  G73	=	'Irregular Path Stock Removal Cycle'
  G74	=	'End Face Grooving Cycle'
  G75	=	'O.D./I.D. Grooving Cycle'
  G76	=	'Threading Cycle, Multiple Pass'
  G80	=	'Canned Cycle Cancel'
  G81	=	'Drill Canned Cycle'
  G82	=	'Spot Drill Canned Cycle'
  G83	=	'Normal Peck Drilling Canned Cycle'
  G84	=	'Tapping Canned Cycle'
  G85	=	'Boring Canned Cycle'
  G86	=	'Bore and Stop Canned Cycle'
  G89	=	'Bore and Dwell Canned Cycle'
  G90	=	'O.D./I.D. Turning Cycle'
  G92	=	'Threading Cycle'
  G94	=	'End Facing Cycle'
  G95	=	'Live Tooling Rigid Tap (Face)'
  G96	=	'Constant Surface Speed On'
  G97	=	'Constant Surface Speed Off'
  G98	=	'Feed Per Minute'
  G99	=	'Feed Per Revolution'
  G100  =	'Disable Mirror Image'
  G101	=	'Enable Mirror Image'
  G103	=	'Limit Block Lookahead'
  G105	=	'Servo Bar Command'
  G107	=	'G107 Cylindrical Mapping'
  G110	=	'Coordinate System #7'
  G111	=	'Coordinate System #8'
  G112	=	'XY to XC Interpolation'
  G113	=	'Cancel G112'
  G114	=	'Coordinate System #9'
  G115	=	'Coordinate System #10'
  G116	=	'Coordinate System #11'
  G117	=	'Coordinate System #12'
  G118	=	'Coordinate System #13'
  G119	=	'Coordinate System #14'
  G120	=	'Coordinate System #15'
  G121	=	'Coordinate System #16'
  G122	=	'Coordinate System #17'
  G123	=	'Coordinate System #18'
  G124	=	'Coordinate System #19'
  G125	=	'Coordinate System #20'
  G126	=	'Coordinate System #21'
  G127	=	'Coordinate System #22'
  G128	=	'Coordinate System #23'
  G129	=	'Coordinate System #24'
  G154	=	'Select Work Coordinates P1-99'
  G156	=	'Broaching Canned Cycle'
  G167	=	'Modify Setting'
  G170	=	'G170 Cancel G171/G172'
  G171	=	'G171 Radius Programming Override'
  G172	=	'G172 Diameter Programming Override'
  G184	=	'Reverse Tapping Canned Cycle For Left Hand Threads'
  G186	=	'Reverse Live Tool Rigid Tap (For Left Hand Threads)'
  G187	=	'Accuracy Control'
  G195	=	'Forward Live Tool Radial Tapping (Diameter)'
  G196	=	'Reverse Live Tool Radial Tapping (Diameter)'
  G198	=	'Disengage Synchronous Spindle Control'
  G199	=	'Engage Synchronous Spindle Control'
  G200	=	'Index on the Fly'
  G211	=	'Manual Tool Setting'
  G212	=	'Auto Tool Setting'
  G234	=	'Tool Center Point Control (TCPC)'
  G241	=	'Radial Drill Canned Cycle'
  G242	=	'Radial Spot Drill Canned Cycle'
  G243	=	'Radial Normal Peck Drilling Canned Cycle'
  G245	=	'Radial Boring Canned Cycle'
  G246	=	'Radial Bore and Stop Canned Cycle'
  G249	=	'Radial Bore and Dwell Canned Cycle'
  G250	=	'Cancel Scaling'
  G251	=	'Scaling'
  G254	=	'Dynamic Work Offset (DWO)'
  G255	=	'Cancel Dynamic Work Offset (DWO)'
  G266	=	'Visible Axes Linear Rapid %Motion'
  G268	=	'Enable Feature Coordinate System'
  G269	=	'Disable Feature Coordinate System'
  G390	=	'Absolute Position Command'
  G391 = 'Incremental Position Command'
  
  return color.YELLOW + eval(g) + color.END
'''
x = 'G' + '391'
print(x)
code = (f'{g}{num}')
return(code)
print(x)
x = get_code('G', 391)
print(code)
'''


if __name__ == '__main__':
  get_code(g)
  